language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_install:
 - cp tests/TestConfiguration.php.travis tests/TestConfiguration.php

script:
 - ant travis -keep-going

after_script:
  - php vendor/bin/coveralls

notifications:
  irc: "irc.freenode.org#zftalk.dev"
  email: false

matrix:
  fast_finish: true
